# Node.js with Angular

# Build a Node.js project that uses Angular.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

pool:
  name: Default

steps:
- task: UseNode@1
  inputs:
    version: '16.15.1'
- task: Npm@1  
  displayName: Build  
  inputs:  
    command: Build  
    verbose: false 
    workingDir: '.'  
    customCommand: 'run build'  
  
- task: CopyPublishBuildArtifacts@1  
  displayName: 'Copy Publish Artifact: test'  
  inputs:  
    CopyRoot: dist  
    Contents: '**'  
    ArtifactName: test  
    ArtifactType: Container  
  
- task: DownloadPipelineArtifact@2  
  displayName: 'Download Pipeline Artifact'  
  inputs:  
    targetPath: ' $(Build.ArtifactStagingDirectory)' 

